import './globals.css'

export const metadata = {
  title: 'Thesis Bani Bak',
  description: 'Generated by Rama',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          Thesis obd by Bani and Bak
        </nav>

        {children}

        
      </body>
    </html>
  )
}
